stages: [check]

.defaults: &defaults
  image: rust:latest
  before_script:
    - rustup component add rustfmt clippy

fmt:
  <<: *defaults
  stage: check
  script:
    - cargo fmt --all --check

clippy:
  <<: *defaults
  stage: check
  script:
    - cargo clippy --workspace --all-targets -- -D warnings

test:
  <<: *defaults
  stage: check
  script:
    - cargo test --workspace
