[workspace]
resolver = "2"
members = [
    "crates/nexus-raw-core",
    "crates/nexus-raw",
    "crates/mock-nexus",
    "crates/nexus-raw-napi",
    "crates/nxr-tui",
]
exclude = ["examples"]

[workspace.package]
version = "0.4.0"
edition = "2021"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/Lipen/nexus-raw"
homepage = "https://github.com/Lipen/nexus-raw"
documentation = "https://lipen.github.io/nexus-raw/"

[workspace.dependencies]
anyhow = "1"
base64 = "0.23"
clap = { version = "4", features = ["derive"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
libc = "0.2"
log = "0.4"
napi = { version = "3", default-features = false, features = ["napi4", "async", "serde-json"] }
napi-build = "2"
napi-derive = "3"
parking_lot = "0.12"
percent-encoding = "2"
reqwest = { version = "0.13", default-features = false, features = ["rustls", "stream", "zstd"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.11"
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "sync", "time", "fs", "io-util", "io-std"] }
toml = "1.1"

[profile.release]
strip = true
lto = true
